config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'users/new'
  get 'sessions/new'
  
  root 'pages#index'
  get 'pages/help'

  resources :users
  resources :topics
  
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get     '/login',  to: 'sessions#new' #login_pathがindex.html.erbにある #get通信で/loginページを呼び出して、同時にsessions newアクションを行っている
  post    '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/introduction.rb
class Introduction < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
  
  belongs_to :user
  
  mount_uploader :image, ImageUploader
  
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true

  has_secure_password
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  helper_method :current_user, :logged_in?
  #before_action :login_required

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
  
  #def login_required
  #  redirect_to login_url unless current_user
  #end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]

    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入りに登録に失敗しました'
    end
  end
  
  def destroy
    favorite_delete = Favorite.find_by(user_id: current_user.id,topic_id: params[:topic_id])

    if favorite_delete.destroy
      redirect_to topics_path, success: '削除に成功しました'
    else
      redirect_to topics_path, danger: '削除に失敗しました'
    end
  end 
  
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #skip_before_action :login_required
  
  def new
    @user = User.new
  end
  
  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      log_in user
      redirect_to user_path(current_user), success:'ログインに成功しました'
    else
      flash.now[:danger]='ログインに失敗しました'
      render :new
    end
  end

 def destroy
   log_out
   redirect_to root_url, info: 'ログアウトしました'
 end

  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all.includes(:favorite_users)
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    
    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

 def show
 @topic = Topic.find_by(id:params[:id]) 
 end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def edit
  end

  def show
  end

  def create

    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger]="登録に失敗しました"
      render :new
    end
  end
  
  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user), success:'更新に成功しました'
    else
      flash.now[:danger]="更新に失敗しました"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email ,:password ,:password_confirmation ,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Polaroyd - Bootstrap Agency Template</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

     <title>Know</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
   <!-- Favicons --> 
  <link href="/img/favicon.png" rel="icon">
  <link href="/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,300,700&subset=latin,cyrillic-ext" rel="stylesheet">


  <!-- =======================================================
    Template Name: Polaroyd
    Template URL: https://templatemag.com/polaroyd-bootstrap-agency-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

  <body>
    
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
    
  </body>
</html>

app/views/layouts/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Polaroyd - Bootstrap Agency Template</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="img/favicon.png" rel="icon">
  <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,300,700&subset=latin,cyrillic-ext" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="lib/ionicons/css/ionicons.min.css" rel="stylesheet">
  <link href="lib/photostack/photostack.css" rel="stylesheet">
  <link href="lib/fullpage-menu/fullpage-menu.css" rel="stylesheet">
  <link href="lib/cubeportfolio/cubeportfolio.css" rel="stylesheet">
  <link href="lib/superslides/superslides.css" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="css/style.css" rel="stylesheet">

  <!-- =======================================================
    Template Name: Polaroyd
    Template URL: https://templatemag.com/polaroyd-bootstrap-agency-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

<body>

  <!-- Custom navbar -->
  <div class="custom-navbar"><a class="fm-button" href="#">Menu</a></div>
  <div class="sidemenu">
    <ul class="fm-first-level">
      <li><a href="#menu1">Main Menu</a></li>
      <li><a href="#menu2">Pages Menu</a></li>
      <li><a href="#menu3">Blog Menu</a></li>
    </ul>
    <nav id="menu1" class="active">
      <a href="index.html">
		    <span class="subtitle">Basic Index. Polaroid header, services, portfolio, clients logos.</span>
		    Main Index Version
		  </a>
      <a href="index2.html">
		    <span class="subtitle">Basic Index with slider. Some objects are removed. Clean Layout.</span>
		    Main Index Variation
		  </a>
      <a href="works.html">
		    <span class="subtitle">Portfolio section. Grid style.</span>
		    Our Works
		  </a>
      <a href="about.html">
		    <span class="subtitle">More information about our agency. Simple & elegant.</span>
		    About Us
		  </a>
      <a href="services.html">
		    <span class="subtitle">List of services provided by us.</span>
		    Services
		  </a>
      <a href="contact.html">
		    <span class="subtitle">We are kind people and love to speak with our clients.</span>
		    Contact Us
		  </a>
    </nav>
    <nav id="menu2">
      <a href="team.html">
		    <span class="subtitle">We are an awesome team. Take a look.</span>
		    Meet The Team
		  </a>
      <a href="single-work.html">
		    <span class="subtitle">Single work page. Information about a project.</span>
		    Single Work
		  </a>
      <a href="clients.html">
		    <span class="subtitle">List of our clients and some cool testimonials.</span>
		    Our Clients
		  </a>
      <a href="pricing.html">
		    <span class="subtitle">A pricing list. Show your prices with style.</span>
		    Pricing
		  </a>
      <a href="404.html">
		    <span class="subtitle">Sometimes errors happens.</span>
		    404
		  </a>
    </nav>
    <nav id="menu3">
      <a href="blog.html">
		    <span class="subtitle">Main blog layout list.</span>
		    Blog List
		  </a>
      <a href="blog-post.html">
		    <span class="subtitle">First variation of blog posts.</span>
		    Blog Post
		  </a>
      <a href="blog-posts-2.html">
		    <span class="subtitle">Second variation of blog posts.</span>
		    Blog Posts 2
		  </a>
    </nav>
  </div>
  <!-- /END CUSTOM NAVBAR -->


  <div class="container">
    <div class="row mt3 presentation">
      <div class="centered">
        <i class="icon ion-ios7-cog-outline large-icon"></i>
        <h1>SERVICES</h1>
        <hr>
      </div>
      <div class="col-lg-4 col-md-4">
        <h3>Our Methodology</h3>
      </div>

      <div class="col-lg-4 col-md-4">
        <p>Dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since, when an unknown ristique senectus et netus.</p>
      </div>

      <div class="col-lg-4 col-md-4">
        <p>Mellentesque habitant morbi tristique senectus et netus et malesuada famesac turpis egestas. Ut non enim eleifend felis pretium feugiat. Vivamus quis mi. Dummy text of the printing and typesetting.</p>
      </div>
    </div>
    <!-- /row -->

    <div class="row mt2">
      <div class="col-md-12 centered">
        <div class="col-md-4 services-bordered">
          <i class="icon ion-ios7-heart-outline large-icon"></i>
          <h4>GRAPHICS DESIGN</h4>
          <p>Sed in porttitor dolor. Sed eleifend vulputate nulla, congue iaculis arcu mattis porta.</p>
        </div>
        <div class="col-md-4 services-bordered">
          <i class="icon ion-ios7-monitor-outline large-icon"></i>
          <h4>WEB DESIGN</h4>
          <p>Sed in porttitor dolor. Sed eleifend vulputate nulla, congue iaculis arcu mattis porta.</p>
        </div>
        <div class="col-md-4 services-bordered">
          <i class="icon ion-ios7-pie-outline large-icon"></i>
          <h4>CODING</h4>
          <p>Sed in porttitor dolor. Sed eleifend vulputate nulla, congue iaculis arcu mattis porta.</p>
        </div>
        <div class="col-md-4 services-bordered">
          <i class="icon ion-ios7-plus-empty large-icon"></i>
          <h4>APPLICATION</h4>
          <p>Sed in porttitor dolor. Sed eleifend vulputate nulla, congue iaculis arcu mattis porta.</p>
        </div>
        <div class="col-md-4 services-bordered">
          <i class="icon ion-ios7-wineglass-outline large-icon"></i>
          <h4>WEB DEVELOPMENT</h4>
          <p>Sed in porttitor dolor. Sed eleifend vulputate nulla, congue iaculis arcu mattis porta.</p>
        </div>
        <div class="col-md-4 services-bordered">
          <i class="icon ion-ios7-lightbulb-outline large-icon"></i>
          <h4>PRODUCTION</h4>
          <p>Sed in porttitor dolor. Sed eleifend vulputate nulla, congue iaculis arcu mattis porta.</p>
        </div>
      </div>
    </div>

    <div class="row mt2">
      <div class="col-md-6 col-md-offset-3 centered presentation">
        <h3>You Should Contact Us</h3>
        <hr>
        <a href="contact.html" class="btn btn-lg btn-theme">Get A Quote</a>

      </div>
    </div>
  </div>

  <section id="contact" class="section-bg-color mt2">
    <div class="container centered ptb">
      <div class="col-md-2 col-md-offset-1">
        <i class="icon ion-ios7-location-outline large-icon"></i>
        <h5>HEAD OFFICE</h5>
        <p>902 Main Street, MVD, UY.</p>
      </div>
      <div class="col-md-2 col-md-offset-2">
        <i class="icon ion-ios7-telephone-outline large-icon"></i>
        <h5>CALL US</h5>
        <p>(598) 123-4567</p>
      </div>
      <div class="col-md-2 col-md-offset-2">
        <i class="icon ion-ios7-paperplane-outline large-icon"></i>
        <h5>QUERIES</h5>
        <p>support@mail.com</p>
      </div>
    </div>
  </section>

  <section id="end" class="section-footer">
    <div class="container centered ptb">
      <div class="col-md-6 col-md-offset-3">
        <h3>Polaroyd Template</h3>
        <p>Mellentesque habitant morbi tristique senectus<br/> et netus et malesuada famesac turpis egestas.</p>
        <p class="mt">
          <a href="#"><i class="fa fa-dribbble"></i></a>
          <a href="#"><i class="fa fa-instagram"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
        </p>
        <p>Copyright &copy; - <strong>Polaroyd</strong> All rights reserved.</p>
        <div class="credits">
          <!--
            You are NOT allowed to delete the credit link to TemplateMag with free version.
            You can delete the credit link only if you bought the pro version.
            Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/polaroyd-bootstrap-agency-template/
            Licensing information: https://templatemag.com/license/
          -->
          Created with Polaroyd template by <a href="https://templatemag.com/">TemplateMag</a>
        </div>
      </div>
    </div>
  </section>

  <!-- JavaScript Libraries -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script src="lib/modernizr/modernizr.min.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script src="lib/php-mail-form/validate.js"></script>
  <script src="lib/easing/easing.min.js"></script>
  <script src="lib/cubeportfolio/cubeportfolio.js"></script>
  <script src="lib/classie/classie.js"></script>
  <script src="lib/fullpage-menu/fullpage-menu.js"></script>
  <script src="lib/photostack/photostack.js"></script>
  <script src="lib/superslides/superslides.js"></script>

  <!-- Template Main Javascript File -->
  <script src="js/main.js"></script>

</body>
</html>

app/views/layouts/index.board.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Polaroyd - Bootstrap Agency Template</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="img/favicon.png" rel="icon">
  <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,300,700&subset=latin,cyrillic-ext" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="lib/ionicons/css/ionicons.min.css" rel="stylesheet">
  <link href="lib/photostack/photostack.css" rel="stylesheet">
  <link href="lib/fullpage-menu/fullpage-menu.css" rel="stylesheet">
  <link href="lib/cubeportfolio/cubeportfolio.css" rel="stylesheet">
  <link href="lib/superslides/superslides.css" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="css/style.css" rel="stylesheet">

  <!-- =======================================================
    Template Name: Polaroyd
    Template URL: https://templatemag.com/polaroyd-bootstrap-agency-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

<body>

<div id="grid-container" class="cbp-l-grid-fullScreen">
    <ul>
      <li class="cbp-item identity">
        <a class="cbp-caption cbp-lightbox" data-title="Image" href="img/works/1.jpg">
          <div class="cbp-caption-defaultWrap">
            <img src="img/works/1.jpg" alt="" class="img-responsive">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <div class="cbp-l-caption-title">Image LightBox</div>
                <div class="cbp-l-caption-desc">by John Doe</div>
              </div>
            </div>
          </div>
        </a>
      </li>
      <!-- end:Item -->
      <li class="cbp-item web-design">
        <a class="cbp-caption cbp-lightbox" data-title="Image" href="img/works/2.jpg">
          <div class="cbp-caption-defaultWrap">
            <img src="img/works/2.jpg" alt="" class="img-responsive">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <div class="cbp-l-caption-title">Image LightBox</div>
                <div class="cbp-l-caption-desc">by John Doe</div>
              </div>
            </div>
          </div>
        </a>
      </li>
      <!-- end:Item -->
      <li class="cbp-item graphic identity">
        <a class="cbp-caption cbp-lightbox" data-title="Image" href="img/works/3.jpg">
          <div class="cbp-caption-defaultWrap">
            <img src="img/works/3.jpg" alt="" class="img-responsive">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <div class="cbp-l-caption-title">Image LightBox</div>
                <div class="cbp-l-caption-desc">by John Doe</div>
              </div>
            </div>
          </div>
        </a>
      </li>
      <!-- end:Item -->
      <li class="cbp-item graphic">
        <a class="cbp-caption cbp-lightbox" data-title="Image" href="img/works/4.jpg">
          <div class="cbp-caption-defaultWrap">
            <img src="img/works/4.jpg" alt="" class="img-responsive">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <div class="cbp-l-caption-title">Image LightBox</div>
                <div class="cbp-l-caption-desc">by John Doe</div>
              </div>
            </div>
          </div>
        </a>
      </li>
      <!-- end:Item -->
      <li class="cbp-item identity">
        <a class="cbp-caption cbp-lightbox" data-title="Image" href="img/works/5.jpg">
          <div class="cbp-caption-defaultWrap">
            <img src="img/works/5.jpg" alt="" class="img-responsive">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <div class="cbp-l-caption-title">Image LightBox</div>
                <div class="cbp-l-caption-desc">by John Doe</div>
              </div>
            </div>
          </div>
        </a>
      </li>
      <!-- end:Item -->
      <li class="cbp-item graphic">
        <a class="cbp-caption cbp-lightbox" data-title="Image" href="img/works/6.jpg">
          <div class="cbp-caption-defaultWrap">
            <img src="img/works/6.jpg" alt="" class="img-responsive">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <div class="cbp-l-caption-title">Image LightBox</div>
                <div class="cbp-l-caption-desc">by John Doe</div>
              </div>
            </div>
          </div>
        </a>
      </li>
      <!-- end:Item -->
      <li class="cbp-item web-design">
        <a class="cbp-caption cbp-lightbox" data-title="Image" href="img/works/7.jpg">
          <div class="cbp-caption-defaultWrap">
            <img src="img/works/7.jpg" alt="" class="img-responsive">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <div class="cbp-l-caption-title">Image LightBox</div>
                <div class="cbp-l-caption-desc">by John Doe</div>
              </div>
            </div>
          </div>
        </a>
      </li>
      <!-- end:Item -->
      <li class="cbp-item identity">
        <a class="cbp-caption cbp-lightbox" data-title="Image" href="img/works/8.jpg">
          <div class="cbp-caption-defaultWrap">
            <img src="img/works/8.jpg" alt="" class="img-responsive">
          </div>
          <div class="cbp-caption-activeWrap">
            <div class="cbp-l-caption-alignCenter">
              <div class="cbp-l-caption-body">
                <div class="cbp-l-caption-title">Image LightBox</div>
                <div class="cbp-l-caption-desc">by John Doe</div>
              </div>
            </div>
          </div>
        </a>
      </li>
    </ul>
  </div>
  
  <!-- JavaScript Libraries -->
  <script src="lib/jquery/jquery.min.js"></script>
  <script src="lib/modernizr/modernizr.min.js"></script>
  <script src="lib/bootstrap/js/bootstrap.min.js"></script>
  <script src="lib/php-mail-form/validate.js"></script>
  <script src="lib/easing/easing.min.js"></script>
  <script src="lib/cubeportfolio/cubeportfolio.js"></script>
  <script src="lib/classie/classie.js"></script>
  <script src="lib/fullpage-menu/fullpage-menu.js"></script>
  <script src="lib/photostack/photostack.js"></script>
  <script src="lib/superslides/superslides.js"></script>

  <!-- Template Main Javascript File -->
  <script src="js/main.js"></script>

</body>
</html>

app/views/layouts/test.html.erb
<!DOCTYPE html>
<html>
  &lt;head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrapをダウンロードファイルから読み込んで使う</title>
    
    <!-- CSS読み込み -->
    <link rel="stylesheet" href="css/bootstrap.css">
  </head>
  <body>
    <h1>Hello World</h1>
 
    <!-- jQuery読み込み JSよりも先に -->
    <script src="jquery-3.4.1.min.js"></script>
    <!-- popper.js js読み込み -->
    <script src="bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/pages/index.html.erb
<body>

  <div class="container">
    <div class="row mt3 presentation">
      <div class="centered">
        <i class="icon ion-ios7-paperplane-outline large-icon"></i>
        <h1>KNOW</h1>
        <hr>
      </div>

       <div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4">
         <p>あなたの世界を写真で表現するアプリ”KNOW”へようこそ！新規登録またはログインをしてください。</p>
       </div>
      </div>
    
  <div class="row">
　　<div class="col-md-6 col-md-offset-3">
     　<div>
      　  <%= link_to 'Sign up', new_user_path, class: 'btn btn-block btn-black' %>
  　 　 </div>
  　　　  <div>
        <%= link_to 'Log in', login_path, class: 'btn btn-block btn-black' %>
       </div>
  　　　  <div>
        <%= link_to '画像投稿', new_topic_path, class: 'btn btn-block btn-black' %>
       </div> 
  　</div>
   </div>
  </div>


  <section id="end" class="section-footer">
    <div class="container centered ptb">
      <div class="col-md-6 col-md-offset-3">
        <h3>Polaroyd Template</h3>
        <p>Mellentesque habitant morbi tristique senectus<br/> et netus et malesuada famesac turpis egestas.</p>
        <p class="mt">
          <a href="#"><i class="fa fa-dribbble"></i></a>
          <a href="#"><i class="fa fa-instagram"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
        </p>
        <p>Copyright &copy; - <strong>Polaroyd</strong> All rights reserved.</p>
        <div class="credits">
          <!--
            You are NOT allowed to delete the credit link to TemplateMag with free version.
            You can delete the credit link only if you bought the pro version.
            Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/polaroyd-bootstrap-agency-template/
            Licensing information: https://templatemag.com/license/
          -->
          Created with Polaroyd template by <a href="https://templatemag.com/">TemplateMag</a>
        </div>
      </div>
    </div>
  </section>

</body>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= link_to '詳細はこちら', topic_path(id: topic.id), class: 'btn btn-block btn-black' %>
            <%= image_tag topic.image.url %>
            
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
              <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <%= image_tag 'icons/heart.png', class: 'topic-index-icon-red' %>
                <% end %>
              <% end %>
            <%= topic.favorite_users.count %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            
            <p class="topic-text">
              <%= topic.description %>
            </p>
            
          </div>
        </div>
      </div>
    <% end %>
       <div>
         <%= link_to '投稿ページへ戻る', new_topic_path, class: 'btn btn-block btn-black' %>
       </div> 
  </div>
</div>

app/views/users/show.html.erb
<p>ユーザーの詳細ページです</p>

<%= current_user.name %>
<h>がログインしています。</h>

<p>ユーザー情報</p>
  <div>
    <h>ユーザーID</h>
    <h><%= current_user.id %></h>
  </div>
  <div>
    <h>ユーザー名</h>
    <h><%= current_user.name %></h>
  </div>
  <div>
    <h>メールアドレス</h>
    <h><%= current_user.email %></h>
  </div>
  <div>
    <h>自己紹介文</h>
    <h><%= current_user.introduction %></h>
  </div>
  
<td><%= link_to 'Edit', edit_user_path(current_user) %></td>